[package]
name = "conway-game-life-ratatui"
version = "0.3.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.31", features = ["derive"] }
color-eyre = "0.6.3"
crossterm = "0.28.1"
log = "0.4.26"
rand = "0.9.0"
ratatui = "0.29.0"
